import './globals.css'
import Heder from "./components/hederCOM/Heder"
import { Vazirmatn } from 'next/font/google'
//
const vazirmatn = Vazirmatn({
  subsets: ['arabic'],
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`h-full w-full ${vazirmatn.className} `} >
        <Heder/>
        {children}
        </body>
    </html>
  )
}
